name: wc_example

environment:
  sdk: '>=3.3.0'

dependencies:
  js: ^0.7.1
  web: ^0.5.1
  webcomponents: any

dependency_overrides:
  webcomponents:
    path: ..

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
